implement FallbackHTTPStatusError filter (fixes #134)
cbsinteractive/bakery pull request #135
Opened 2021-01-31 04:14 UTC by flavioribeiro

2021-02-01 20:16 UTC, zsiec commented on handlers/handler.go
> +				case parsers.ProtocolVTT:
The switch now on line 67 will not set a filter for the `vtt` "protocol" causing a panic when `f.FilterManifest` is called on line 77.

2021-02-01 20:19 UTC, zsiec commented on handlers/handler.go
> +				case parsers.ProtocolVTT:
Also, I wonder if we should rename `manifestInfo` as it can contain media/variant manifest content, mpd content or VTT cues?

2021-02-01 20:19 UTC, zsiec commented on docs/filters/prevent-http-status-error.md
> +title: Prevent HTTP Error
<3 docs!!

2021-02-01 20:21 UTC, zsiec commented on filters/hls.go
> +const EmptyHLSManifestContent = "#EXTM3U"
Just curious, I wonder if there's any case we've seen where an "empty" HLS would avoid an error in playback.

2021-02-01 20:26 UTC, zsiec commented on origin/origin.go
> +		path = decodedPath
It's odd we call this `path`, in many (if not most?) cases, won't this be the full url?

2021-02-01 20:28 UTC, zsiec commented on origin/origin.go
> +	encodedPath = strings.TrimSuffix(encodedPath, filepath.Ext(encodedPath))
we might want `path.Ext` as `filepath` assumes path separators based on the os execution context.

2021-02-01 20:35 UTC, zsiec requested changes
Added a few comments, I assume re-writing the vtt subtitle manifests to use bakery urls for vtt segments is out-of-scope, perhaps Dictate will already do this ahead of time?

2021-02-01 21:58 UTC, keithrichardscbs commented on filters/vtt.go
> +const EmptyVTTContent = "WEBVTT"
In Dictate this is what we return for empty vtt:
`"WEBVTT\nX-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:0\n\nNOTE No timecoded transcript received. No captions generated.\n"`

The timestamp stuff I have found helps Apple players. The Note of course we could change to something that would help identify that it came from bakery.

2021-02-02 14:53 UTC, flavioribeiro commented on filters/hls.go
> +const EmptyHLSManifestContent = "#EXTM3U"
Anecdotally, a service (like dictate) could error out on creating the `en.m3u8` for the vtt renditions but still retry and create it over time. If we serve an empty manifest instead of erroring the request out, we could potentially still recover that player that initiated the session when the real manifest wasn't still there. If we serve the 404 all the way back, some players will remove or quarantine that rendition during the playback.

Note that a lot of what I wrote isn't tested and based on assumptions. My idea was to defer to the "client" (in this case, dictate) in whether to protect a request or not. Does that make sense?

2021-02-02 14:59 UTC, flavioribeiro commented on origin/origin.go
> +	encodedPath = strings.TrimSuffix(encodedPath, filepath.Ext(encodedPath))
good catch

2021-02-02 15:05 UTC, flavioribeiro commented on filters/vtt.go
> +const EmptyVTTContent = "WEBVTT"
pretty useful stuff, thanks @keithrichardscbs

2021-02-02 15:16 UTC, flavioribeiro commented on handlers/handler.go
> +				case parsers.ProtocolVTT:
> The switch now on line 67 will not set a filter for the vtt "protocol" causing a panic when f.FilterManifest is called on line 77 because f is nil.

The code will never reach line 77 as it will return _something_ if the request to the origin errors out. However, I agree with you things can become hard to manage as we have "filters" that don't act as filters. Should we have a `NewVTTFilter` on `vtt.go` that just returns the plain vtt cue and conform with the others?

> Also, I wonder if we should rename manifestInfo as it can contain media/variant manifest content, mpd content or VTT cues?

I think so. Can we go with `Content`? `Payload`? We'll need to change the `FetchManifest` function on `origin` and a few other things to conform to this change.

2021-02-02 15:17 UTC, flavioribeiro commented
Thanks to the comments, @zsiec, and @keithrichardscbs. I updated the PR with the suggestions and replied to some others.

2021-02-02 15:31 UTC, zsiec commented on handlers/handler.go
> +				case parsers.ProtocolVTT:
Won't it reach line 77 if the origin doesn't error?

2021-02-02 15:35 UTC, zsiec commented on handlers/handler.go
> +				case parsers.ProtocolVTT:
`OriginResponse` as a name perhaps?

This is the struct as it stands:
```go
//ManifestInfo holds http response info from manifest request
type ManifestInfo struct {
	Manifest     string
	LastModified time.Time
	Status       int
}
```

+1 on renaming the surrounding subroutines/structs

2021-02-02 15:36 UTC, zsiec commented on handlers/handler.go
> +				case parsers.ProtocolVTT:
>  Should we have a NewVTTFilter on vtt.go that just returns the plain vtt cue and conform with the others?

yeah I think this makes sense, it might be just a passthrough for now, but we can add manipulation there if we ever need it

2021-02-02 15:43 UTC, zsiec commented on origin/origin.go
> +		url, err := trimAndDecodePath(strings.TrimPrefix(path, "/"))
Odd Go thing, I try to avoid using variables that collide with stdlib go package names, this could be `u` or `originURL` or something?

2021-02-02 15:45 UTC, zsiec requested changes
Most of my remaining comments are stylistic. Would approve except, I want to confirm the logic is correct in the happy path and won't cause panics.

2021-02-07 14:47 UTC, flavioribeiro commented on origin/origin.go
> +		url, err := trimAndDecodePath(strings.TrimPrefix(path, "/"))
totally, thanks for catching this one!

2021-02-11 18:50 UTC, flavioribeiro commented on handlers/handler.go
> +				case parsers.ProtocolVTT:
this should be solved now

2021-02-12 04:22 UTC, zsiec commented on origin/origin.go
> +	encodedPath = strings.TrimSuffix(encodedPath, filepath.Ext(encodedPath))
did we lose changes here? I thought you changed this in recent commit

2021-02-12 04:23 UTC, zsiec reviewed
Added a comment, not sure if we lost some changes in the rebase

2021-02-12 21:11 UTC, flavioribeiro commented on origin/origin.go
> +	encodedPath = strings.TrimSuffix(encodedPath, filepath.Ext(encodedPath))
yeah that seems to be the case, I'm seeing the changes in 7f18ab87

2021-02-12 21:13 UTC, flavioribeiro commented on origin/origin.go
> +	encodedPath = strings.TrimSuffix(encodedPath, filepath.Ext(encodedPath))
I cherry picked that one, but very interesting observation, I'm going over everything now to see if we lost changes. The fact is that I coded this one in two different computers, so that might have caused some issues

2021-02-16 19:26 UTC, zsiec approved these changes
LGTM!

2021-02-16 23:50 UTC, merged