Bakery v2 include filters
cbsinteractive/bakery pull request #191
Opened 2022-03-30 17:26 UTC by JackDunham

**Summary**
Add `include` and `include-first` filter-options, per [Bakery 2.0 Spec
](https://www.notion.so/videotechnologygroup/Bakery-Internal-b13753ccc9074d9598c5c3d387abac4c#1ec9c3598089494392a1b9d0a5383706)

**Linked Issues**
#178
#188
#189
#190

2022-03-30 18:47 UTC, terranvigil commented
Looks like some tests are failing. Also, if you merge in my branch or master, those annoying inline comments from codecov will go away.

2022-04-01 18:57 UTC, terranvigil commented on filters/dash.go
> +			// TODO(jack): do stuff here, depending on option
Is the TODO work tracked by a separate ticket? Generally, approving a PR means it's ready to be merged to main and go to dev. But if this is more of a review to get feedback, then we prefix the PR name with "WIP:" and ignore the TODOs and just make comments but don't approve the PR.

2022-04-01 19:00 UTC, terranvigil commented on filters/dash.go
> +							// subsequent matching codes
codecs? SP

2022-04-01 19:20 UTC, terranvigil commented
Code looks good and great tests. CI is failing due to linters.

2022-04-07 16:49 UTC, JackDunham commented
Testing PR notification emails.

2022-04-11 17:35 UTC, JackDunham commented on filters/dash.go
> +			// TODO(jack): do stuff here, depending on option
Crufty comment, actually.

2022-04-11 17:37 UTC, JackDunham commented on filters/dash.go
> +			// TODO(jack): do stuff here, depending on option
Fixed

2022-04-11 17:37 UTC, JackDunham commented on filters/dash.go
> +							// subsequent matching codes
Fixed

2022-04-11 19:38 UTC, terranvigil commented on filters/dash.go
> +							continue
Shouldn't this break instead of continue?

2022-04-11 19:42 UTC, terranvigil commented on filters/dash.go
> -			switch ContentType(*as.ContentType) {
Just curious, why the change from switch to if/else? The former seems more concise.

2022-04-11 19:43 UTC, terranvigil commented on filters/dash.go
> +			if filterOption == parsers.FilterOptionIncludeFirst { // nolint:nestif
If this linter isn't providing help, maybe add to the ignore list? We can always move it back and see if it's worth restructuring nested if statements.

2022-04-11 21:21 UTC, JackDunham commented on filters/dash.go
> -			switch ContentType(*as.ContentType) {
One guess: lint was complaining.

2022-04-11 21:23 UTC, JackDunham commented on filters/dash.go
> +			if filterOption == parsers.FilterOptionIncludeFirst { // nolint:nestif
As w/ everything lint -- I don't mind keeping it on, and occasionally disabling it, on an as-needed basis. If we're disabling it everywhere, then -- yes -- should add ignore-list.

2022-04-11 21:31 UTC, JackDunham commented on filters/dash.go
> +							continue
Nope -- we still need to process the all the representations in the AdaptationSet -- we just don't need to bother w/ the subsequent logic, in the loop.

2022-04-12 14:12 UTC, terranvigil commented on filters/dash.go
> +
Could also use a switch statement to avoid the comparisons.

2022-04-12 14:15 UTC, terranvigil commented on filters/dash.go
> +							continue
Ah, is that because of the "handleSpecialCodecs" piece?

2022-04-12 14:16 UTC, terranvigil commented on filters/dash.go
> -			switch ContentType(*as.ContentType) {
Hmm, it shouldn't. I know it will complain if you only have a single "case" but that's not true here.

2022-04-12 14:18 UTC, terranvigil commented on filters/dash_test.go
> +	manifestWithAccessibilityElement := readTestFixtures("manifest_with_accessibility_element.mpd")
thank you for not putting the manifests inline ... so much easier to read when they area test fixture!

2022-04-12 14:19 UTC, terranvigil commented on filters/dash_test.go
> +					Codecs:       []string{"avc", "dvh"},
Could all of these values be constants in filters/common.go?

2022-04-12 14:36 UTC, terranvigil commented on filters/hls.go
> +			case "dvs":
Now this is where I'd expect a linter to complain. Could be changed to:
```
if chr == "dvs" && alternative.Characteristics == dvsCharacteristics {
	vari.VariantParams.Alternatives = append(vari.VariantParams.Alternatives[:idx], vari.VariantParams.Alternatives[idx+1:]...)
	filtered = true
	break
}
```

2022-04-12 14:46 UTC, terranvigil commented on filters/hls.go
> +	res, filterOptionsState, err := filterByContentType(videoContentType, filters.Videos.Codecs, variantCodecs,
Don't have a strong opinion on this one but wasn't sure if you knew the other form for this:
```
if res, filterOptionsState, err := filterByContentType(videoContentType, ... filterOptionsState); res {
	return res, filterOptionsState, err
}
```

2022-04-12 14:58 UTC, terranvigil commented on filters/hls.go
> +	res, filterOptionsState, err = filterByContentType(audioContentType, filters.Audios.Codecs, variantCodecs,
I haven't read far enough to understand why this would make sense but without the context or comment, it's confusing to see `filters.Videos.FilterOption` used in filtering audio.

2022-04-12 15:00 UTC, terranvigil commented on filters/hls.go
> +	res, filterOptionsState, err = filterByContentType(captionContentType, filters.Captions.Codecs, variantCodecs,
And here

2022-04-12 15:02 UTC, terranvigil commented on filters/hls.go
> +		if filterOptions == parsers.FilterOptionInclude {
Could && the compares here and below to avoid the extra nesting.

2022-04-12 15:05 UTC, terranvigil commented on logging/logging_test.go
> +// No-op test
Is this just a place-holder for future tests? Otherwise no value.

2022-04-12 15:15 UTC, terranvigil commented on parsers/urlparser.go
> +					if k == nf {
Simplify by doing:
```
if _, found := characteristicsSupported[nf] {
    break;
} else {
    return keyError("Characteristics", nil)
}
```

2022-04-12 15:17 UTC, terranvigil commented on parsers/urlparser.go
> +				// For our purposes, this is OK (currently) because (per Jignesh) all HEVC content is assumed to be HDR
This just doesn't feel right. Jignesh isn't our only customer and we will continue to add customers.

2022-04-12 15:17 UTC, terranvigil commented on tests/tests_test.go
> +package tests
???

2022-04-12 15:18 UTC, terranvigil requested changes
Overall, looks great. Had a couple comments, questions and suggestions.

2022-04-12 15:20 UTC, JackDunham commented on filters/dash.go
> +							continue
That and...part of how include vs exclude now works.

2022-04-12 15:24 UTC, terranvigil commented on filters/dash.go
> -			switch ContentType(*as.ContentType) {
Ah, that's lame. That's the whole point of default. I do get why you might want to not rely on a default and force new possible values to force revisiting the logic, but there is probably a better way.

2022-04-12 16:30 UTC, JackDunham commented on filters/dash_test.go
> +	manifestWithAccessibilityElement := readTestFixtures("manifest_with_accessibility_element.mpd")
👍

2022-04-12 16:33 UTC, JackDunham commented on filters/hls.go
> +	res, filterOptionsState, err = filterByContentType(audioContentType, filters.Audios.Codecs, variantCodecs,
Oh my, no! That's gotta be an error...Why does it pass all the tests...? Good catch

2022-04-12 16:41 UTC, JackDunham commented on filters/hls.go
> +	res, filterOptionsState, err = filterByContentType(audioContentType, filters.Audios.Codecs, variantCodecs,
Where is that happening?

2022-04-12 16:52 UTC, JackDunham commented on filters/hls.go
> +	res, filterOptionsState, err = filterByContentType(audioContentType, filters.Audios.Codecs, variantCodecs,
Ah, yeah -- that's all fine. It's because:

2022-04-12 16:59 UTC, JackDunham commented on filters/hls.go
> +	res, filterOptionsState, err = filterByContentType(audioContentType, filters.Audios.Codecs, variantCodecs,
Included a comment, re: use/purpose of FilterOptionsState

2022-04-12 16:59 UTC, JackDunham commented on filters/hls.go
> +	res, filterOptionsState, err = filterByContentType(captionContentType, filters.Captions.Codecs, variantCodecs,
See comment attached to `filterVariant` method, re: use/purpose of FilterOptionsState

2022-04-12 17:12 UTC, JackDunham commented on filters/hls.go
> +		if filterOptions == parsers.FilterOptionInclude {
This is true...but I don't know that it makes the code any more readable. IMHO, judicious use of nested IFs can be _more_ readable.

2022-04-12 17:16 UTC, JackDunham commented on parsers/urlparser.go
> +					if k == nf {
Here's my thinking (here and above, where you suggested removing the range over characteristics): I can easily imagine a short-term future where there's more than one characteristic we need to handle.

2022-04-12 17:18 UTC, JackDunham commented on parsers/urlparser.go
> +				// For our purposes, this is OK (currently) because (per Jignesh) all HEVC content is assumed to be HDR
Oh, for sure it's not "right". But it's def. what @jigneshdhruv indicated that _want_. (They _know_ it's not "right". That also promise any hvc1.2/hev1.2 we see _will_ be 10-bit color).

2022-04-12 17:19 UTC, JackDunham commented on tests/tests_test.go
> +package tests
More monkey-tricks for getting this linter to stop complaining about no tests for a module...even when that module is a test-fixture directory.

2022-04-12 17:21 UTC, JackDunham commented on tests/tests_test.go
> +package tests
It's definitely something than can be sorted out in the `Makefile`...

2022-04-12 17:25 UTC, JackDunham commented on filters/dash.go
> -			switch ContentType(*as.ContentType) {
Yeah...linters in general seem to err on overly-aggressive side...¯\_(ツ)_/¯ Everything taken w/ a grain of salt...

2022-04-12 17:36 UTC, terranvigil commented on filters/dash.go
> +
```
switch (filterOption) {
}
```
And then //nolint:whatever that is complaining about not listing out all options

2022-04-12 17:45 UTC, terranvigil commented on parsers/urlparser.go
> +					if k == nf {
My bias is based on our tendency to treat each new project as an emergency and never get back to filling in features, leaving lots of TODOs and FIXMEs in the code. But I hear you.

2022-04-12 18:12 UTC, terranvigil commented on parsers/urlparser.go
> +				// For our purposes, this is OK (currently) because (per Jignesh) all HEVC content is assumed to be HDR
hvc/hev1.2.4 will always bee Main10 and therefore 10-bit. Still makes me really uncomfortable. Maybe add a note to the docs about this one so we can at least says  "We warned you".

2022-04-12 20:30 UTC, JackDunham commented on filters/dash_test.go
> +					Codecs:       []string{"avc", "dvh"},
Fixed.

2022-04-12 21:07 UTC, JackDunham commented on parsers/urlparser.go
> +		if partsDict["option"] == "i" {
Fixed.

2022-04-12 21:58 UTC, JackDunham commented on parsers/urlparser.go
> +					if k == nf {
Found a better way to express this, actually.  Calling it fixed.

2022-04-13 04:49 UTC, JackDunham commented on filters/hls.go
> +	res, filterOptionsState, err := filterByContentType(videoContentType, filters.Videos.Codecs, variantCodecs,
Yeah --I'm definitely _aware_ of it. And I know it's one of the "Go-ier" of all the Go idioms. I just don't find it makes anything more readable.

2022-04-13 04:54 UTC, JackDunham commented on filters/dash.go
> +
Changed.

2022-04-13 05:43 UTC, JackDunham commented on filters/hls.go
> +			case "dvs":
Changed.

2022-04-13 11:01 UTC, terranvigil approved these changes
LGTM!

2022-04-13 18:02 UTC, merged